### ISSUE TITLE
Wrong messahes when getting existing Chatmessages

### ISSUE THREAD

**Issue by rootzoll** [konfetti-app/konfetti-backend#13]
GET http://localhost:3000/api/chats/channel/5a5d1de70902c30503c2b2e8/since/0
Liefert immer alle Chatmessages von allen Chats
Die ParentUser sind teilweise null, wenn sie einen Wert haben, dann sind dort teil keine "namen" vom Autor drin den ich anzeigen kann

**Comment by piezzo** [comment]
parentUser ist leer weil der Datenbestandalt ist und dies noch nicht vorsah. Der rest folgt. :)
