### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by peters1977** [konfetti-app/konfetti-backend#15]
Hello,

Im trying to run the konfetti backend but I had the following mistakes:

Loading api-route: assets.js
Loading api-route: authenticate.js
Loading api-route: chats.js
Loading api-route: codes.js
Loading api-route: neighbourhoods.js
Loading api-route: posts.js
Loading api-route: subscriptions.js
Loading api-route: threads.js
Loading api-route: users.js
connected to mongodb://localhost/konfetti.
(node:8949) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: not authorized for query on konfetti.sys                                      tem.indexes
(node:8949) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled wil                                      l terminate the Node.js process with a non-zero exit code.
new socket connection: patrick Cw8iyAM23AOBW2R_AAAA
(node:8949) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): MongoError: not authorized for query on konfetti.sys                                      tem.indexes
(node:8949) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): MongoError: not authorized for query on konfetti.sys                                      tem.indexes
(node:8949) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): MongoError: not authorized for query on konfetti.sys                                      tem.indexes
(node:8949) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): MongoError: not authorized for query on konfetti.sys                                      tem.indexes
(node:8949) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): MongoError: not authorized for query on konfetti.sys                                      tem.indexes

Could you please suggest me how can I solve it?

Thank you very much.

**Comment by piezzo** [comment]
Hi there,

> MongoError: not authorized for query on konfetti.sys tem.indexes

This indicates your database is not set up do accept queries. Are you setting it (mongo) from sratch? Which commit are you using?

Cheers,
-patrick

**Comment by piezzo** [comment]
closed.
