### ISSUE TITLE
newsfeed needs to filter for neighborhood id

### ISSUE THREAD

**Issue by rootzoll** [konfetti-app/konfetti-backend#16]
Actual newsfeed endpoint looks like this
localhost:3000/api/newsfeed/
and returns all news posts for a user on all neighborhoods member of

Please add a filter, that the app can only requests posts related one neighborhood
localhost:3000/api/newsfeed/5a7ff9e81fa76a68520aae52

**Comment by piezzo** [comment]
should be in b5ecc012914611724789af8527b553308a82a016, needs testing

**Comment by piezzo** [comment]
fixed in 66ed806b2a4cc23e764b14028c543ae15643645c
