### ISSUE TITLE
Endpoint to interact on Konfetti Idea as User

### ISSUE THREAD

**Issue by rootzoll** [konfetti-app/konfetti-backend#20]
joinKonfettiIdea(ideaID:string, attent:boolean, helping:boolean)
--> that way a user can attend, help or cancel attending or help

result should be the resulting state of help and attending

export interface JoinResult {
  isAttending:boolean;
  isHelping:boolean;
}

**Comment by rootzoll** [comment]
Possible Bug: On my tests today I was able to become a helper on a idea but was not able to remove myself from the helper status anymore. 

Also when I become helper I see myself in the helpers array. But when I attend .. I dont see myself in the subscribers array. Or there is no guests array either.

**Comment by piezzo** [comment]
handled differerently. We return arrays of helpers and guests
