### ISSUE TITLE
Local Backend is not starting

### ISSUE THREAD

**Issue by geco91** [konfetti-app/konfetti-backend#23]
After a fresh checkout on my computer I did a npm install and started up a fresh mongo DB.

Then when with starting it local with "node bin/www" I get a Exception ... see:
![bildschirmfoto 2018-03-18 um 23 57 47](https://user-images.githubusercontent.com/16744217/37572256-ac223174-2b08-11e8-9486-74f44bcd3069.png)

Also it would be great to document how to init the mongoDB data structure. Thx.

**Comment by piezzo** [comment]
Hi There.

which node version are you running?
We are cuurrently developing on node 9; ist should run on node 6, it will definitely not run in lower versions.

**Comment by geco91** [comment]
It was node 6.9.5 ... upgraded to 9.11.1 ... now its working. thx

**Comment by piezzo** [comment]
Thanks for sharing this insight. I’ll update the documentation to reflect this. 

Best, Patrick
